version: '3.8'

services:
  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_BACKEND_URL=http://node-backend:4000
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./vector_store:/app/vector_store
    depends_on:
      - node-backend
    restart: unless-stopped

  node-backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/zentraChatbot}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data:
